import { Router } from "express";
import { DB, pool, qid } from "../../config/db";
import { asyncHandler } from "../../middleware/asyncHandler";
import { getClientIdFromProcess } from "../../utils/db";

const router = Router();

type QueryRows = any[];
type ColumnInfo = { COLUMN_NAME: string; DATA_TYPE: string };
type FieldSpec = { key: string; label: string; required: boolean; candidates: string[]; purpose: string };
type FieldMapping = FieldSpec & { found_column: string | null; data_type: string | null; status: "FOUND" | "MISSING_REQUIRED" | "MISSING_OPTIONAL" };
type MappingResult = { fields: FieldMapping[]; byKey: Record<string, FieldMapping>; summary: Record<string, any> };
type AuditConcern = { type: string; severity: "Critical" | "High" | "Medium" | "Coaching"; field: string; value: any; note: string };

const AUDIT_TABLE = "call_quality_assessment";

const INBOUND_FIELD_SPECS: FieldSpec[] = [
  { key: "client_id", label: "Client ID", required: true, candidates: ["ClientId", "client_id", "clientid", "client"], purpose: "Process-to-client filtering" },
  { key: "call_date", label: "Call Date", required: true, candidates: ["CallDate", "call_date", "created_at", "audit_date", "call_datetime", "Date"], purpose: "Date filtering and sorting" },
  { key: "agent_name", label: "Agent / User Name", required: false, candidates: ["AgentName", "agent_name", "UserName", "user_name", "EmpName", "employee_name", "agent", "Agent Name"], purpose: "Agent ranking and drilldown" },
  { key: "user_id", label: "User ID", required: false, candidates: ["UserID", "user_id", "userid", "employee_id", "emp_code", "EmpCode", "User ID"], purpose: "Audit identity" },
  { key: "lead_id", label: "Lead / Call ID", required: false, candidates: ["LeadID", "lead_id", "lead", "source_call_id", "call_id", "CallId", "id", "Lead ID"], purpose: "Call audit drilldown identity" },
  { key: "phone_no", label: "Phone Number", required: false, candidates: ["PhoneNo", "phone_no", "mobile", "customer_mobile", "customer_phone", "caller_number", "ani", "Phone No"], purpose: "Repeat analysis and drilldown fallback" },
  { key: "scenario", label: "Scenario", required: false, candidates: ["Scenario", "scenario", "call_scenario", "CallScenario"], purpose: "Scenario-wise analysis" },
  { key: "sub_scenario", label: "Sub Scenario", required: false, candidates: ["SubScenario", "sub_scenario", "subscenario", "sub_scenario_name", "Sub Scenario"], purpose: "Sub-scenario analysis" },
  { key: "quality_score", label: "CQ / Quality Score", required: true, candidates: ["quality_percentage", "cq_score", "quality_score", "quality_percent", "qualitypercentage", "score", "CQ Score%"], purpose: "CQ score KPI and ranking" },
  { key: "fatal_count", label: "Fatal Count / Flag", required: false, candidates: ["fatal_count", "fatal", "fatal_status", "fatal_error", "fatal_flag", "Fatal Count"], purpose: "Fatal count and percentage" },
  { key: "sensitive_word", label: "Sensitive Word", required: false, candidates: ["sensetive_word", "sensitive_word", "Sensitive Word Used", "sensitive_words", "sensitive_word_count", "negative_words"], purpose: "Sensitive word KPI and transcript highlight" },
  { key: "policy_failure", label: "Policy Communication Failure", required: false, candidates: ["policy_communication_failure", "policy_failure", "policy_failure_count", "policycommunicationfailure"], purpose: "Policy failure KPI" },
  { key: "area_for_improvement", label: "Area for Improvement", required: false, candidates: ["Area for Improvement", "area_for_improvement", "area_improvement", "improvement_area", "coaching_area", "audit_remarks"], purpose: "Coaching notes and transcript concern context" },
  { key: "transcript", label: "Transcript", required: false, candidates: ["Transcribe Text", "transcribe_text", "transcript", "transcription", "call_transcript", "call_text"], purpose: "Call transcript" },
  { key: "competitor", label: "Competitor Name", required: false, candidates: ["Competitor Name", "competitor_name", "CompetitorName", "competitor"], purpose: "Competitor intelligence" },
  { key: "opening_score", label: "Opening Score", required: false, candidates: ["opening_score", "opening", "call_opening_score", "Opening Score%"], purpose: "Looker quality score breakdown" },
  { key: "soft_skill_score", label: "Soft Skill Score", required: false, candidates: ["soft_skill_score", "softskill_score", "soft_skills_score", "soft_skill", "Soft Skills Score"], purpose: "Looker quality score breakdown" },
  { key: "hold_procedure_score", label: "Hold Procedure Score", required: false, candidates: ["hold_procedure_score", "hold_score", "holdprocedure_score", "Hold Procedure Score%"], purpose: "Looker quality score breakdown" },
  { key: "resolution_score", label: "Resolution Score", required: false, candidates: ["resolution_score", "resolution", "query_resolution_score", "Resolution Score%"], purpose: "Looker quality score breakdown" },
  { key: "closing_score", label: "Closing Score", required: false, candidates: ["closing_score", "closing", "call_closing_score", "Closing Score%"], purpose: "Looker quality score breakdown" },
];

const PARAMETER_KEYWORDS = ["acknowledged", "professionalism", "assurance", "appreciation", "empathy", "pronunciation", "clarity", "enthusiasm", "fumbling", "active", "listening", "politeness", "sarcasm", "grammar", "probing", "hold", "transfer", "language", "address", "information", "closure"];
const CONCERN_TERMS = ["consumer court", "legal notice", "social media", "complaint", "refund", "return", "exchange", "delay", "failure", "inconvenience", "frustration", "dissatisfaction", "not received", "not delivered", "cancel", "scam", "fraud", "threat", "abuse", "slang", "escalation", "angry", "policy", "pending", "no update"];

function normaliseColumnName(value: string): string { return value.toLowerCase().replace(/[^a-z0-9]/g, ""); }
function colid(column: string | null | undefined): string | null { if (!column || column.includes("`")) return null; return `\`${column}\``; }
function sqlString(column: string): string { return `LOWER(TRIM(CAST(${column} AS CHAR)))`; }
function numeric(column: string): string { return `CAST(${column} AS DECIMAL(18,4))`; }
function found(mapping: MappingResult, key: string): string | null { return colid(mapping.byKey[key]?.found_column); }
function rawColumn(mapping: MappingResult, key: string): string | null { return mapping.byKey[key]?.found_column || null; }
function getValue(row: Record<string, any>, mapping: MappingResult, key: string): any { const column = rawColumn(mapping, key); return column ? row[column] : undefined; }
function valueLooksPositive(value: any): boolean { if (value === null || value === undefined) return false; const text = String(value).trim().toLowerCase(); if (["", "no", "none", "null", "n/a", "na", "0", "false"].includes(text)) return false; const num = Number(text); return Number.isNaN(num) || num > 0; }
function valueLooksFailure(value: any): boolean { if (value === null || value === undefined) return false; const text = String(value).trim().toLowerCase(); return ["false", "no", "n", "0", "fail", "failed", "incorrect", "not followed", "not done", "missing"].includes(text); }
function labelFromColumn(column: string): string { return column.replace(/[_-]+/g, " ").replace(/([a-z])([A-Z])/g, "$1 $2").replace(/\s+/g, " ").trim().replace(/\b\w/g, (m) => m.toUpperCase()); }

async function safeQuery<T>(sql: string, params: any[], fallback: T): Promise<T> { try { const [rows]: any = await pool.query(sql, params); return rows as T; } catch (err) { console.warn("Inbound dynamic query skipped:", err instanceof Error ? err.message : err); return fallback; } }
async function getAuditColumns(): Promise<ColumnInfo[]> { const sql = `SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? ORDER BY ORDINAL_POSITION`; const [rows]: any = await pool.query(sql, [DB.AUDIT, AUDIT_TABLE]); return rows || []; }
async function getInboundFieldMapping(): Promise<MappingResult> {
  const columns = await getAuditColumns(); const lookup = new Map<string, ColumnInfo>(); for (const col of columns) lookup.set(normaliseColumnName(col.COLUMN_NAME), col);
  const fields: FieldMapping[] = INBOUND_FIELD_SPECS.map((spec) => { const match = spec.candidates.map((candidate) => lookup.get(normaliseColumnName(candidate))).find(Boolean) as ColumnInfo | undefined; const foundColumn = match?.COLUMN_NAME || null; return { ...spec, found_column: foundColumn, data_type: match?.DATA_TYPE || null, status: foundColumn ? "FOUND" : spec.required ? "MISSING_REQUIRED" : "MISSING_OPTIONAL" }; });
  const byKey = fields.reduce<Record<string, FieldMapping>>((acc, item) => { acc[item.key] = item; return acc; }, {}); const required = fields.filter((f) => f.required); const optional = fields.filter((f) => !f.required); const mappedRequired = required.filter((f) => f.found_column).length; const mappedOptional = optional.filter((f) => f.found_column).length;
  return { fields, byKey, summary: { table_schema: DB.AUDIT, table_name: AUDIT_TABLE, total_required: required.length, mapped_required: mappedRequired, missing_required: required.length - mappedRequired, total_optional: optional.length, mapped_optional: mappedOptional, missing_optional: optional.length - mappedOptional, readiness_percent: Math.round((fields.filter((f) => f.found_column).length / (fields.length || 1)) * 10000) / 100 } };
}
function buildWhere(mapping: MappingResult, clientId: number, date?: string): { sql: string; params: any[]; dateApplied: boolean } { const clientCol = found(mapping, "client_id"); const dateCol = found(mapping, "call_date"); const clauses: string[] = []; const params: any[] = []; let dateApplied = false; if (clientCol) { clauses.push(`${clientCol} = ?`); params.push(clientId); } else clauses.push("1 = 0"); if (date && dateCol) { clauses.push(`DATE(${dateCol}) = ?`); params.push(date); dateApplied = true; } return { sql: `WHERE ${clauses.join(" AND ")}`, params, dateApplied }; }
function buildKpiSelect(mapping: MappingResult): string { const qualityCol = found(mapping, "quality_score"); const fatalCol = found(mapping, "fatal_count"); const sensitiveCol = found(mapping, "sensitive_word"); const policyCol = found(mapping, "policy_failure"); const cqExpr = qualityCol ? `ROUND(AVG(${numeric(qualityCol)}), 2)` : "0"; const fatalExpr = fatalCol ? `SUM(CASE WHEN COALESCE(${numeric(fatalCol)}, 0) > 0 OR ${sqlString(fatalCol)} IN ('yes','y','true','fatal','fail','failed','1') THEN 1 ELSE 0 END)` : "0"; const sensitiveExpr = sensitiveCol ? `SUM(CASE WHEN ${sensitiveCol} IS NOT NULL AND ${sqlString(sensitiveCol)} NOT IN ('','no','none','null','n/a','na','0') THEN 1 ELSE 0 END)` : "0"; const policyExpr = policyCol ? `SUM(CASE WHEN COALESCE(${numeric(policyCol)}, 0) > 0 OR ${sqlString(policyCol)} IN ('yes','y','true','fail','failed','1') THEN 1 ELSE 0 END)` : "0"; return `COUNT(*) AS audit_count, ${cqExpr} AS cq_score, ${fatalExpr} AS fatal_count, ${sensitiveExpr} AS sensitive_word_count, ${policyExpr} AS policy_failure_count`; }
function extractAuditConcerns(row: Record<string, any>, mapping: MappingResult): { concerns: AuditConcern[]; transcript: string; area_for_improvement: string; highlight_terms: string[]; parameter_status: any[] } {
  const concerns: AuditConcern[] = []; const transcript = String(getValue(row, mapping, "transcript") || ""); const area = String(getValue(row, mapping, "area_for_improvement") || ""); const sensitive = getValue(row, mapping, "sensitive_word"); const policy = getValue(row, mapping, "policy_failure"); const fatal = getValue(row, mapping, "fatal_count");
  if (valueLooksPositive(fatal)) concerns.push({ type: "Fatal Trigger", severity: "Critical", field: rawColumn(mapping, "fatal_count") || "fatal", value: fatal, note: "Fatal/error flag is present for this call." });
  if (valueLooksPositive(policy)) concerns.push({ type: "Policy Communication Failure", severity: "High", field: rawColumn(mapping, "policy_failure") || "policy_failure", value: policy, note: "Policy communication failure is present." });
  if (valueLooksPositive(sensitive)) concerns.push({ type: "Sensitive Word", severity: "High", field: rawColumn(mapping, "sensitive_word") || "sensitive_word", value: sensitive, note: "Sensitive word or phrase is present and should be reviewed in transcript." });
  if (area.trim()) concerns.push({ type: "Area for Improvement", severity: "Coaching", field: rawColumn(mapping, "area_for_improvement") || "area_for_improvement", value: area, note: "Auditor/AI coaching area captured for this call." });
  const parameterStatus = Object.entries(row).filter(([column]) => PARAMETER_KEYWORDS.some((keyword) => normaliseColumnName(column).includes(normaliseColumnName(keyword)))).map(([column, value]) => ({ column, label: labelFromColumn(column), value, status: valueLooksFailure(value) ? "Concern" : valueLooksPositive(value) ? "Pass" : "Blank" }));
  for (const item of parameterStatus.filter((p) => p.status === "Concern")) concerns.push({ type: "Parameter Miss", severity: "Coaching", field: item.column, value: item.value, note: `${item.label} appears missed/failed and should be checked against transcript.` });
  const highlightTerms = new Set<string>(); for (const term of CONCERN_TERMS) highlightTerms.add(term); if (valueLooksPositive(sensitive)) String(sensitive).split(/[,|;]+/).map((x) => x.trim()).filter(Boolean).forEach((x) => highlightTerms.add(x)); if (area.trim()) area.split(/[^A-Za-z0-9]+/).filter((x) => x.length > 5).slice(0, 12).forEach((x) => highlightTerms.add(x));
  return { concerns, transcript, area_for_improvement: area, highlight_terms: Array.from(highlightTerms).filter(Boolean), parameter_status: parameterStatus };
}

router.get("/:processCode/schema-check", asyncHandler(async (req, res) => { const { processCode } = req.params; const clientId = await getClientIdFromProcess(processCode); const mapping = await getInboundFieldMapping(); res.json({ success: true, processCode, clientId, data: mapping }); }));
router.get("/:processCode/call-audit/:identifier", asyncHandler(async (req, res) => {
  const { processCode, identifier } = req.params; const clientId = await getClientIdFromProcess(processCode); const mapping = await getInboundFieldMapping();
  if (!clientId) return res.status(404).json({ success: false, message: "No client mapping found for process", processCode });
  const clientCol = found(mapping, "client_id"); const actualColumns = new Set((await getAuditColumns()).map((c) => c.COLUMN_NAME));
  const identifierColumns = [rawColumn(mapping, "lead_id"), rawColumn(mapping, "phone_no"), rawColumn(mapping, "user_id")].filter(Boolean).filter((value, index, arr) => arr.indexOf(value) === index).filter((column) => actualColumns.has(column || "")).map((column) => colid(column || "")).filter(Boolean) as string[];
  if (!clientCol || !identifierColumns.length) return res.status(400).json({ success: false, message: "Required client/identifier column mapping missing", schema: mapping.summary });
  const clauses = identifierColumns.map((column) => `CAST(${column} AS CHAR) = ?`); const sql = `SELECT * FROM ${qid(DB.AUDIT)}.${qid(AUDIT_TABLE)} WHERE ${clientCol} = ? AND (${clauses.join(" OR ")}) LIMIT 1`; const params = [clientId, ...identifierColumns.map(() => identifier)]; const rows = await safeQuery<QueryRows>(sql, params, []); const row = rows?.[0];
  if (!row) return res.status(404).json({ success: false, message: "Call audit row not found", processCode, identifier });
  const extracted = extractAuditConcerns(row, mapping); const summary = { call_date: getValue(row, mapping, "call_date"), lead_id: getValue(row, mapping, "lead_id") || row.id, agent_name: getValue(row, mapping, "agent_name"), user_id: getValue(row, mapping, "user_id"), phone_no: getValue(row, mapping, "phone_no"), scenario: getValue(row, mapping, "scenario"), sub_scenario: getValue(row, mapping, "sub_scenario"), cq_score: getValue(row, mapping, "quality_score"), fatal: getValue(row, mapping, "fatal_count"), sensitive_word: getValue(row, mapping, "sensitive_word"), policy_failure: getValue(row, mapping, "policy_failure"), competitor: getValue(row, mapping, "competitor") };
  res.json({ success: true, processCode, clientId, identifier, data: { summary, row, schema: mapping.summary, concerns: extracted.concerns, transcript: extracted.transcript, area_for_improvement: extracted.area_for_improvement, highlight_terms: extracted.highlight_terms, parameter_status: extracted.parameter_status, columns: Object.keys(row) } });
}));
router.get("/:processCode/quality", asyncHandler(async (req, res) => { const { processCode } = req.params; const date = req.query.date as string | undefined; const clientId = await getClientIdFromProcess(processCode); if (!clientId) return res.json({ success: true, processCode, data: { audit_count: 0, cq_score: 0, fatal_count: 0, sensitive_word_count: 0, policy_failure_count: 0 } }); const mapping = await getInboundFieldMapping(); const where = buildWhere(mapping, clientId, date); const rows = await safeQuery<QueryRows>(`SELECT ${buildKpiSelect(mapping)} FROM ${qid(DB.AUDIT)}.${qid(AUDIT_TABLE)} ${where.sql}`, where.params, []); res.json({ success: true, processCode, clientId, schema: mapping.summary, data: rows?.[0] || {} }); }));
router.get("/:processCode/looker-parity", asyncHandler(async (req, res) => {
  const { processCode } = req.params; const date = req.query.date as string | undefined; const clientId = await getClientIdFromProcess(processCode); const mapping = await getInboundFieldMapping();
  if (!clientId) return res.json({ success: true, processCode, clientId: null, data: { schema: mapping, kpis: { audit_count: 0, cq_score: 0, fatal_count: 0, fatal_percent: 0, target_cq: 85, sensitive_word_count: 0, policy_failure_count: 0 }, score_breakdown: [], agent_rank: [], raw_audits: [] } });
  const where = buildWhere(mapping, clientId, date); const kpiRows = await safeQuery<QueryRows>(`SELECT ${buildKpiSelect(mapping)} FROM ${qid(DB.AUDIT)}.${qid(AUDIT_TABLE)} ${where.sql}`, where.params, []); const rawKpis = kpiRows?.[0] || {}; const auditCount = Number(rawKpis.audit_count || 0); const fatalCount = Number(rawKpis.fatal_count || 0); const kpis = { audit_count: auditCount, cq_score: Number(rawKpis.cq_score || 0), fatal_count: fatalCount, fatal_percent: auditCount > 0 ? Number(((fatalCount / auditCount) * 100).toFixed(2)) : 0, target_cq: 85, sensitive_word_count: Number(rawKpis.sensitive_word_count || 0), policy_failure_count: Number(rawKpis.policy_failure_count || 0) };
  const scoreFields = ["opening_score", "soft_skill_score", "hold_procedure_score", "resolution_score", "closing_score"]; const scoreSelects = scoreFields.map((key) => { const col = found(mapping, key); return col ? `ROUND(AVG(${numeric(col)}), 2) AS ${qid(key)}` : null; }).filter(Boolean); const scoreRows = scoreSelects.length ? await safeQuery<QueryRows>(`SELECT ${scoreSelects.join(",\n")} FROM ${qid(DB.AUDIT)}.${qid(AUDIT_TABLE)} ${where.sql}`, where.params, []) : []; const score = scoreRows?.[0] || {}; const score_breakdown = scoreFields.map((key) => ({ code: key, label: mapping.byKey[key]?.label || key, column: mapping.byKey[key]?.found_column, score: score[key] })).filter((item) => item.column && item.score !== null && item.score !== undefined);
  const agentCol = found(mapping, "agent_name"); const agentRank = agentCol ? await safeQuery<QueryRows>(`SELECT ${agentCol} AS agent_name, ${buildKpiSelect(mapping)} FROM ${qid(DB.AUDIT)}.${qid(AUDIT_TABLE)} ${where.sql} GROUP BY ${agentCol} ORDER BY cq_score ASC, fatal_count DESC, policy_failure_count DESC LIMIT 25`, where.params, []) : [];
  const rawSelects = [["client_id", "client_id"], ["call_date", "call_date"], ["agent_name", "agent_name"], ["user_id", "user_id"], ["lead_id", "lead_id"], ["phone_no", "phone_no"], ["scenario", "scenario"], ["sub_scenario", "sub_scenario"], ["quality_score", "cq_score"], ["fatal_count", "fatal_count"], ["sensitive_word", "sensitive_word"], ["policy_failure", "policy_failure"], ["area_for_improvement", "area_for_improvement"]].map(([key, alias]) => { const col = found(mapping, key); return col ? `${col} AS ${qid(alias)}` : null; }).filter(Boolean); const dateCol = found(mapping, "call_date"); const rawAudits = rawSelects.length ? await safeQuery<QueryRows>(`SELECT ${rawSelects.join(",\n")} FROM ${qid(DB.AUDIT)}.${qid(AUDIT_TABLE)} ${where.sql} ${dateCol ? `ORDER BY ${dateCol} DESC` : ""} LIMIT 50`, where.params, []) : [];
  res.json({ success: true, processCode, clientId, data: { schema: mapping, date_filter_applied: where.dateApplied, kpis, score_breakdown, agent_rank: agentRank, raw_audits: rawAudits } });
}));

export default router;
